#!/usr/bin/env python3
"""Generate the bundled Millipede caster's config from .env, and write back a
mountpoint password for any station that does not have one yet.

Run by caster/setup.sh after the caster is built; safe to re-run (idempotent -
an existing STREAM_CASTER_PASSWORDS entry is kept, never regenerated, so a
re-run to add a station does not invalidate every other station's already-
provisioned credential). See caster/README.md.

Reads STREAM_CASTER_STATIONS (which stations to provision) and STREAM_CASTER_PORT
from .env; writes STREAM_CASTER_PASSWORDS and STREAM_CASTER_ENABLE=true back into
.env, and (over)writes caster.yaml / sourcetable.dat / source.auth / blocklist /
host.auth under caster/millipede-caster/etc/.
"""

import secrets
import sys
from pathlib import Path

from dotenv import dotenv_values, set_key

CASTER_DIR = Path(__file__).resolve().parent
REPO_DIR = CASTER_DIR.parent
ENV_FILE = REPO_DIR / ".env"
BUILD_DIR = CASTER_DIR / "millipede-caster"
ETC_DIR = BUILD_DIR / "etc"
LOG_DIR = BUILD_DIR / "var" / "log"

# The RTCM3 types a typical single-band-to-multi-constellation rover set needs.
# Only advertised in the sourcetable for humans/clients browsing it - has no
# effect on what NtripCasterSink actually forwards (that is whatever the
# demuxer decodes for the station, unfiltered).
_DEFAULT_MSG_TYPES = "1005,1077,1087,1097,1127,1230"


def _parse_stations(value: str) -> list[int]:
    return sorted({int(s) for s in (p.strip() for p in value.replace(";", ",").split(",")) if s.isdigit()})


def _parse_passwords(value: str) -> dict[int, str]:
    result: dict[int, str] = {}
    for pair in value.replace(";", ",").split(","):
        station, _, password = pair.partition(":")
        station, password = station.strip(), password.strip()
        if station.isdigit() and password:
            result[int(station)] = password
    return result


def main() -> None:
    if not ENV_FILE.exists():
        sys.exit(f"{ENV_FILE} not found - copy .env.example to .env and set "
                  "STREAM_CASTER_STATIONS first")

    env = dotenv_values(ENV_FILE)
    stations = _parse_stations(env.get("STREAM_CASTER_STATIONS", ""))
    if not stations:
        sys.exit("STREAM_CASTER_STATIONS is empty in .env - set it to the "
                  "station id(s) that should get a mountpoint, e.g. "
                  "STREAM_CASTER_STATIONS=1001")
    port = int(env.get("STREAM_CASTER_PORT", "2101") or "2101")

    passwords = _parse_passwords(env.get("STREAM_CASTER_PASSWORDS", ""))
    for station in stations:
        if station not in passwords:
            passwords[station] = secrets.token_urlsafe(18)

    ETC_DIR.mkdir(parents=True, exist_ok=True)
    LOG_DIR.mkdir(parents=True, exist_ok=True)

    _write_caster_yaml(port)
    _write_sourcetable(stations)
    _write_source_auth(stations, passwords)
    (ETC_DIR / "blocklist").touch(exist_ok=True)
    (ETC_DIR / "host.auth").touch(exist_ok=True)  # only used by proxy mode, which we don't set

    passwords_value = ",".join(f"{s}:{p}" for s, p in sorted(passwords.items()))
    set_key(str(ENV_FILE), "STREAM_CASTER_PASSWORDS", passwords_value, quote_mode="never")
    set_key(str(ENV_FILE), "STREAM_CASTER_ENABLE", "true", quote_mode="never")

    print(f"Wrote {ETC_DIR} (stations: {stations})")
    print(f"Updated {ENV_FILE}: STREAM_CASTER_ENABLE=true, "
          f"STREAM_CASTER_PASSWORDS for {sorted(passwords)}")


def _write_caster_yaml(port: int) -> None:
    (ETC_DIR / "caster.yaml").write_text(f"""\
# Generated by caster/generate_config.py - re-run it to regenerate, don't
# hand-edit (it will be overwritten). See caster/README.md.
listen:
  - port: {port}
    ip:   0.0.0.0

host_auth_file:    {ETC_DIR / "host.auth"}
blocklist_file:    {ETC_DIR / "blocklist"}
source_auth_file:  {ETC_DIR / "source.auth"}
sourcetable_file:  {ETC_DIR / "sourcetable.dat"}

access_log:  {LOG_DIR / "access.log"}
log:         {LOG_DIR / "caster.log"}
log_level:   INFO
""")


def _write_sourcetable(stations: list[int]) -> None:
    lines = []
    for station in stations:
        # Field 12 (nmea/"virtual base" in Millipede's own reading of it) MUST
        # be 0 - see caster/README.md's "Mount Point Taken" trap. Position is
        # a placeholder (0.00;0.00): it only matters for Millipede's NEAR/
        # virtual-base lookup, which this setup does not use. Fill in the
        # station's real position later (from its own RTCM 1005 ARP) if you
        # start using that feature.
        lines.append(
            f"STR;{station};station-{station};RTCM3;{_DEFAULT_MSG_TYPES};2;"
            f"GPS+GLO+GAL+BDS;NONE;NONE;0.00;0.00;0;0;wormhole;none;N;N;1200;"
        )
    (ETC_DIR / "sourcetable.dat").write_text("\n".join(lines) + "\n")


def _write_source_auth(stations: list[int], passwords: dict[int, str]) -> None:
    lines = [
        f"{station}:wormhole:{passwords[station]}"
        for station in stations
    ]
    path = ETC_DIR / "source.auth"
    path.write_text("\n".join(lines) + "\n")
    path.chmod(0o600)


if __name__ == "__main__":
    main()
